# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: 'Build and deploy Node.js app to Azure Web App: thunderboard-api'

on:
  push:
    branches:
    - main
    paths:
    - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5

    - name: Set up Node.js version
      uses: actions/setup-node@v5
      with:
        node-version: '22.x'

    - name: npm install, build, and test
      working-directory: backend
      env:
      AZURE_DATABASE_URL: ${{ secrets.AZURE_DATABASE_URL }}
        AZURE_STORAGE_URL: ${{ secrets.AZURE_STORAGE_URL }}
        AZURE_STORAGE_EVENTS_CONTAINER_NAME: event-images
        AZURE_STORAGE_ORGANIZATION_CONTAINER_NAME: organization-logos
        AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
        AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
      run: |
        npm ci
        npm run build --if-present
        npm run test --if-present

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'thunderboard-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fdc1a8c4406447e192c5bb73b52943c6 }}
        package: backend
